### ISSUE TITLE
mjc_example fails on second iteration

### ISSUE THREAD

**Issue by wmontgomery4** [cbfinn/gps#2]
When running the peg insertion mjc_example, the trajectory optimizer fails on the second step because it cannot regularize with very large eta:

`ValueError: Failed to find PD solution even for very large eta (check that dynamics and cost are reasonably well conditioned)!`

The issue seems to be condition 3, which actually increases cost in the first update:
![image](https://cloud.githubusercontent.com/assets/1236981/13542781/20c5cc5a-e21a-11e5-8800-fd81de78d745.png)

**Comment by cbfinn** [comment]
I just pushed a change to the master branch that should fix this issue.

**Comment by wmontgomery4** [comment]
Thanks! It's working now.

**Comment by Tveek** [comment]
@wmontgomery4 @cbfinn  how can you set up the MuJoCo? I can not down it .can you give me some help? are you using Windows or Linux?

**Comment by wmontgomery4** [comment]
@DemoRunner I'm working on Linux, but Mujoco is proprietary software that you need a license to use.
