### ISSUE TITLE
how can i use GPS to deal with propblems that the target point is changging 

### ISSUE THREAD

**Issue by jjkke88** [cbfinn/gps#46]
Can i use GPS to train a model that can fit to different target point?

**Comment by cbfinn** [comment]
Please post questions like this to [gps-help](https://groups.google.com/forum/#!forum/gps-help), not as an issue on github.

To answer your question -- you can either add the target point to the state representation, or express some components of the state representation to be relative to the target. Both of these options enable the algorithm to handle different target points.
