### ISSUE TITLE
Problem in using MuJoCo131 trial license

### ISSUE THREAD

**Issue by happyzgp** [cbfinn/gps#47]
Hi, I try to use MuJoCo131 trial license with GPS, but on running the mjc_example experiment, it will output:

ERROR: Invalid activation key

The trial license works well with MuJoCo's own simulate program. 

Does anyone know the reason? Thanks!

**Comment by cbfinn** [comment]
You may want to make sure that the key is in the correct directory. Otherwise, I don't know what would cause the issue.

**Comment by happyzgp** [comment]
Hi Chelsea, thanks for your comments. I put the key in the path 'gps/src/3rdparty/mjpro/mjkey.txt', is that OK? Where should I put the key? or is it because I use the the trial version? Thanks!

**Comment by cbfinn** [comment]
That should be fine. I haven't tried using the trial version before, so I don't know if it would cause issues.

**Comment by cbfinn** [comment]
I would recommend contacting mujoco developers: http://www.mujoco.org/contact.html

**Comment by happyzgp** [comment]
Hi Chelsea, thank you. I will check it out.

**Comment by acrosson** [comment]
@happyzgp how did you resolve?

**Comment by flyingdust777** [comment]
@happyzgp were you able to resolve this?

**Comment by newuhe** [comment]
I encounter the problem`Could not open activation key file src/3rdparty/mjpro/mjkey.txt`
