### ISSUE TITLE
there does not exit the file: gps.algorithm.policy_opt.config_tf 

### ISSUE THREAD

**Issue by amoliu** [cbfinn/gps#8]
When verifying the test_policy_opt_tf.py, I meet the following errors:

  from gps.algorithm.policy_opt.config_tf import POLICY_OPT_TF
ImportError: No module named config_tf

Thanks

**Comment by cbfinn** [comment]
I believe that line should instead be:
from gps.algorithm.policy_opt.config import POLICY_OPT_TF

**Comment by bstadie** [comment]
Fixed #9
