### ISSUE TITLE
pilqr: does it need installation of ROS to run door opening task? 

### ISSUE THREAD

**Issue by haoliuhl** [cbfinn/gps#96]
Hi, 

Thanks for sharing code, at [here](https://github.com/cbfinn/gps/blob/master/experiments/mjc_door_opening_pilqr/hyperparams.py#L36) I see PR2 configuration, while at PILQR paper, this task is said to be a mujoco simulation task. I am a little bit confused by this, could anyone help me clear this?

**Comment by cbfinn** [comment]
No, it should not require ROS. The simulated robot is modeled after the PR2

**Comment by haoliuhl** [comment]
@cbfinn Thanks.
